site_name: LegisPro
repo_url: https://github.com/mdsreq-fga-unb/REQ-2025.2-T02-ProJuris.git
site_url: https://mdsreq-fga-unb.github.io/REQ-2025.2-T02-ProJuris/
site_dir: site

nav:
  - Home: index.md
  - Entregas:
    - 'Unidade 1': 'Entregas/Unidade 1.md'
    - 'Unidade 2': 'Entregas/Unidade 2.md'
    - 'Atividades de Casos de Uso':
      - 'Estudo de Caso':
        - 'Caso de Uso':
          - 'Visão Geral': 'Entregas/Estudos de Caso/Caso de Uso.md'
          - 'Gerenciar Estoque': 'Entregas/Estudos de Caso/Especificacoes/GerenciarEstoque.md'
          - 'Autenticar Usuário': 'Entregas/Estudos de Caso/Especificacoes/AutenticarUsuario.md'
          - 'Solicitar Serviços': 'Entregas/Estudos de Caso/Especificacoes/SolicitarServicos.md'
          - 'Rastrear Solicitações': 'Entregas/Estudos de Caso/Especificacoes/RastrearSolicitacoes.md'
          - 'Candidatar-se para Curso': 'Entregas/Estudos de Caso/Especificacoes/CandidatarCurso.md'
          - 'Consultar Usuários': 'Entregas/Estudos de Caso/Especificacoes/ConsultarUsuarios.md'
      - 'PBB': 'Entregas/Estudos de Caso/PBB.md'
      - 'USM': 'Entregas/Estudos de Caso/USM.md'
  - Evidências:
    - 'Atas':
      - '15-09': 'Evidências/Atas/3_15-09.md'
      - '22-09': 'Evidências/Atas/4_22-09.md'
      - '06-10': 'Evidências/Atas/6_06-10.md'
      - '13-10': 'Evidências/Atas/8_13-10.md'
      - '03-11': 'Evidências/Atas/11_03-11.md'
      - '10-11': 'Evidências/Atas/12_10-11.md'
      - '24-11': 'Evidências/Atas/13_24-11.md'
    - 'Diagrama Caso de Uso': 'Evidências/Diagrama Caso de Uso.md'
    - 'Prints Protótipo': 'Evidências/Prints Prototipo.md'
    - 'Reuniões com o cliente': 'Evidências/Reuniao Cliente.md'
  - MVP: 'MVP.md'
  - Requisitos:
    - 'Funcionais': 'Requisitos/Funcionais.md'
    - 'Não Funcionais': 'Requisitos/Não funcionais.md'
    - 'Work Item List': 'Requisitos/Work Item List.md'
  - Caso de Uso:
    - 'Diagrama Caso de Uso': 'Requisitos/Diagrama Caso de Uso.md'
    - Especificações de Caso de Uso:
      - 'UC-01 — Criar Demanda': 'Requisitos/Especificações de Caso de Uso/Criar Demandas.md'
      - 'UC-02 — Tramitar Demanda': 'Requisitos/Especificações de Caso de Uso/Tramitar Demanda.md'
      - 'UC-03 — Cadastrar Usuário': 'Requisitos/Especificações de Caso de Uso/Cadastrar Usuário.md'
      - 'UC-04 — Editar Detalhe das Demandas': 'Requisitos/Especificações de Caso de Uso/Editar detalhe das demandas.md'
  - Visão do Produto e Projeto:
    - 'Cenário Atual': 'Visão do produto e projeto/1 CENÁRIO ATUAL DO CLIENTE E DO NEGÓCIO.md'
    - Engenharia de Requisitos: 'Visão do produto e projeto/2 Engenharia de Requisitos.md'
    - 'Solução Proposta': 'Visão do produto e projeto/3 SOLUÇÃO PROPOSTA.md'
    - 'Estratégias de Engenharia': 'Visão do produto e projeto/4 ESTRATÉGIAS DE ENGENHARIA DE SOFTWARE.md'
    - DoR e DoD: 'Visão do produto e projeto/5 DoR e DoD.md'
    - 'Cronograma e Entregas': 'Visão do produto e projeto/6 CRONOGRAMA E ENTREGAS.md'
    - 'Interação Equipe e Cliente': 'Visão do produto e projeto/7 INTERAÇÃO ENTRE EQUIPE E CLIENTE.md'
    - 'Lições Aprendidas': 'Visão do produto e projeto/8 LIÇÕES APRENDIDAS.md'
    - 'Referências': 'Visão do produto e projeto/9 REFERÊNCIAS BIBLIOGRÁFICAS.md'

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode